name: build-image

on:
  push:
    branches: [ main, centos-mpi ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mccoygroup/mcenv:centos-mpi
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}